version: '2'
services:
  web:
    volumes:
      - ./html:/var/www/html
      - ./db:/src/db

    environment:
      VIRTUAL_HOST:     redaxo4-sample.dkr
      MAIL_RECEIVER:    no-reply@businesstools.de
      NODE_ENV:         development
